name: abrak
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter 

  bloc: ^9.0.0
  geolocator: ^13.0.2
  weather: ^3.1.1  
  intl: ^0.20.2
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/images/
  


  fonts:
    - family: dana
      fonts:
        - asset: assets/fonts/vb.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
